//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingRichard.Bot.Modules.WordFilter {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KingRichard.Bot.Modules.WordFilter.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фильтр {0} успешно добавлен..
        /// </summary>
        internal static string FilterAdded {
            get {
                return ResourceManager.GetString("FilterAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фильтр успешно удален..
        /// </summary>
        internal static string FilterRemoved {
            get {
                return ResourceManager.GetString("FilterRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регулярное выражение задано некорректно..
        /// </summary>
        internal static string IsNotValidRegex {
            get {
                return ResourceManager.GetString("IsNotValidRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на *!#&amp;?.
        /// </summary>
        internal static string ObsceneWords {
            get {
                return ResourceManager.GetString("ObsceneWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на \w{0,5}[хx]([хx\s\!@#$%\^&amp;*+-\|\/]{0,6})[уy]([уy\s\!@#$%\^&amp;*+-\|\/]{0,6})[ёiлeеюийя]\w{0,7}|\w{0,6}[пp]([пp\s\!@#$%\^&amp;*+-\|\/]{0,6})[iие]([iие\s\!@#$%\^&amp;*+-\|\/]{0,6})[3зс]([3зс\s\!@#$%\^&amp;*+-\|\/]{0,6})[дd]\w{0,10}|[сcs][уy]([уy\!@#$%\^&amp;*+-\|\/]{0,6})[4чkк]\w{1,3}|\w{0,4}[bб]([bб\s\!@#$%\^&amp;*+-\|\/]{0,6})[lл]([lл\s\!@#$%\^&amp;*+-\|\/]{0,6})[yя]\w{0,10}|\w{0,8}[её][bб][лске@eыиаa][наи@йвл]\w{0,8}|\w{0,4}[еe]([еe\s\!@#$%\^&amp;*+-\|\/]{0,6})[бb]([бb\s\!@#$%\^&amp;*+-\|\/]{0,6})[uу]([uу\s\!@#$%\^&amp;*+-\|\/]{0,6})[н4ч]\w{0,4 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ObsceneWordsRegex {
            get {
                return ResourceManager.GetString("ObsceneWordsRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сообщение было удалено в связи с использованием запрещенных слов..
        /// </summary>
        internal static string RemoveMessege {
            get {
                return ResourceManager.GetString("RemoveMessege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сообщение было удалено в связи с использованием нецензурной лексики..
        /// </summary>
        internal static string RemoveMessegeByObscene {
            get {
                return ResourceManager.GetString("RemoveMessegeByObscene", resourceCulture);
            }
        }
    }
}
