//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingRichard.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filter
    {
        public int Id { get; set; }
        public string Regex { get; set; }
        public long GuildId { get; set; }
    
        public virtual Guild Guild { get; set; }
    }
}
