//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingRichard.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectRichardDBEntities : DbContext
    {
        public ProjectRichardDBEntities()
            : base("name=ProjectRichardDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RoleConformity> RoleConformities { get; set; }
        public virtual DbSet<Guild> Guilds { get; set; }
        public virtual DbSet<BlockedCommand> BlockedCommands { get; set; }
        public virtual DbSet<BlockedModule> BlockedModules { get; set; }
        public virtual DbSet<Filter> Filters { get; set; }
        public virtual DbSet<Session> Sessions { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<ApplicationLog> ApplicationLogs { get; set; }
        public virtual DbSet<VoiceChannel> VoiceChannels { get; set; }
        public virtual DbSet<VoiceChannelLog> VoiceChannelLogs { get; set; }
        public virtual DbSet<Advertising> Advertisings { get; set; }
    }
}
