//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingRichard.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoiceChannelLog
    {
        public int Id { get; set; }
        public long UserId { get; set; }
        public long VoiceChannelId { get; set; }
        public System.DateTime Time { get; set; }
    
        public virtual User User { get; set; }
        public virtual VoiceChannel VoiceChannel { get; set; }
    }
}
