//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingRichard.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoiceChannel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VoiceChannel()
        {
            this.VoiceChannelLogs = new HashSet<VoiceChannelLog>();
        }
    
        public long Id { get; set; }
        public long GuildId { get; set; }
        public string Name { get; set; }
    
        public virtual Guild Guild { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VoiceChannelLog> VoiceChannelLogs { get; set; }
    }
}
